[build]
    command = "npm run build" 
    publish = "/build" 
    functions = "functions/"

[[redirects]]
  from="/functions"
  to="/.netlify/functions/:splat"
  status=200

[[redirects]]
    from = "/*" 
    to = "/index.html" 
    status = 200 