[build]
    command ="npm run build"
    publish = "/build"
    functions = "/server"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"