[build]
    command = "npm run build" 
    publish = "/build" 
    functions = "functions"

[[redirects]]
    from = "/functions" 
    to = "/functions" 
    status = 200 
    
[[redirects]]
    from = "/netlify/functions" 
    to = "/functions" 
    status = 200 

[[redirects]]
    from = "/*" 
    to = "/index.html" 
    status = 200 
    
